//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desummer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class dataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Desummer.dataResource", typeof(dataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time, A로 온도, B로 온도, C로 온도
        ///2021-01-08 0:00,721,729,700
        ///2021-01-08 0:05,720,729,699
        ///2021-01-08 0:10,720,729,700
        ///2021-01-08 0:15,720,730,700
        ///2021-01-08 0:20,720,730,700
        ///2021-01-08 0:25,720,730,700
        ///2021-01-08 0:30,720,730,700
        ///2021-01-08 0:35,720,730,700
        ///2021-01-08 0:40,720,731,700
        ///2021-01-08 0:45,720,731,700
        ///2021-01-08 0:50,720,731,700
        ///2021-01-08 0:55,720,730,700
        ///2021-01-08 1:00,720,730,699
        ///2021-01-08 1:05,720,730,700
        ///2021-01-08 1:10,720,730,699
        ///2021-01-08 1:15,720,730,700
        ///2021-01-08 1:20,720,7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string termalFurnace {
            get {
                return ResourceManager.GetString("termalFurnace", resourceCulture);
            }
        }
    }
}
